# Topology 1 (Gossipsub-based Model) specific configuration

topology: 1  # Specifies which topology implementation to use

# Override topology1 parameters
topology1:
  num_subnets: 128
  signatures_in_aggregation_portion: 0.9  # 90%
  num_subnet_aggregators: 16
  num_global_aggregators: 128
  num_peers_with_all_roles: 0
  # Gossipsub specific parameters
  gossipsub_D: 8
  gossipsub_D_low: 6
  gossipsub_D_high: 12
  gossipsub_heartbeat_interval_ms: 700
  gossipsub_mesh_outbound_min: 4
  gossipsub_fanout_ttl_seconds: 60

# Optional: Override simulation parameters
simulation:
  max_time_seconds: 300  # Maximum simulation time in seconds

# Optional: Override network parameters if needed for gossipsub performance
network:
  network_latency_min_ms: 10
  network_latency_max_ms: 100
  network_latency_distribution: "normal"

# Optional: Metrics configuration specific to this topology
metrics:
  collect_bandwidth_usage: true
  collect_message_counts: true
  collect_latency: true
  log_interval_ms: 1000